# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Site settings
title: "Projects by BC"
description: > # this means to ignore newlines until "email:"
   A place for projects from coding to filmmaking
email: hello@bodhiconnolly.com
#blog logo
logo: "/assets/images/BC.jpg"
# blog cover
cover: "/assets/images/roof1.jpg"
404: "/assets/images/404.jpg"
bottomcover: "/assets/images/desk.jpg"

name: 'Bodhi Connolly'
author: 'Bodhi Connolly'
author_image: "/assets/images/author.jpg"

paginate:	100

url: "http://projects.bodhiconnolly.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
 
   - icon:	twitter
    url:	http://twitter.com/bodhiconnolly
    desc:	Follow me on Twitter
    share_url:
    share_title:
    share_link:
 
  - icon:	linkedin
    url:	http://linkedin.com/in/bodhiconnolly
    desc:	Connect on LinkedIn
    share_url:
    share_title:
    share_link:
 
 
  - icon:	instagram
    url:	https://instagram.com/bodhiconnolly
    desc:	Follow me on Instagram
    share_url:
    share_title:
    share_link:

	 - icon:	youtube
    url:	https://youtube.com/user/bodhiconnolly
    desc:	Subscribe on YouTube
    share_url:
    share_title:
    share_link:
	


