# Build settings
markdown: redcarpet
highlighter: pygments

# Site 'Bodhi Connolly'
description: > # this means to ignore newlines until "email:"
   A place to document projects from filmmaking to coding