# Build settings
markdown: redcarpet
highlighter: pygments

# Site 'Bodhi Connolly'
description: > # this means to ignore newlines until "email:"
    A place to document projects from filmmaking to coding

email: 'contact@bodhiconnolly.com'
#blog logo
logo: "/assets/images/BC.jpg"
# blog cover
cover: "/assets/images/code.jpg"
name: 'Bodhi Connolly'
author: 'Bodhi Connolly'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://bodhiconnolly.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
# social:
  # - icon:	twitter
    # url:	https://twitter.com/dirkfabisch
    # desc: Follow me on twitter
    # share_url: http://twitter.com/share
    # share_title: ?text=
    # share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

- icon: youtube
  url: https://youtube.com/user/bodhiconnolly
  desc: Add me on youtube
  share_url:
  share_title:
  share_link:



- icon:	instagram
  url:	http://instagram.com/bodhiconnolly
  desc:	Fork me on instagram
  share_url:
  share_title:
  share_link:

- icon:	github
  url:	https://github.com/bodhiconnolly
  desc:	Fork me on github
  share_url:
  share_title:
  share_link:


	
	