# Build settings
markdown: redcarpet
highlighter: pygments

# Site 'Bodhi Connolly'
description: > # this means to ignore newlines until "email:"
   A place to document projects from filmmaking to coding
   
email: 'contact@bodhiconnolly.com'
#blog logo
logo: "/assets/images/BC.jpg"
# blog cover
cover: "/assets/images/code.jpg"
name: 'Bodhi Connolly'
author: 'Bodhi Connolly'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://bodhiconnolly.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
# social:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title:
#    share_link:

- icon:	github
  url:	https://github.com/bodhiconnolly
  desc:	Fork me on github
  share_url:
  share_title:
  share_link: