# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Site settings
title: "Bodhi Connolly"
description: > # this means to ignore newlines until "email:"
   A place for projects from coding to filmmaking
email: contact@bodhiconnolly.com
#blog logo
logo: "/assets/images/BC.jpg"
# blog cover
cover: "/assets/images/roof1.jpg"
404: "/assets/images/404.jpg"
bottomcover: "/assets/images/desk.jpg"

name: 'Bodhi Connolly'
author: 'Bodhi Connolly'
author_image: "/assets/images/author.jpg"

paginate:	100

url: "http://bodhiconnolly.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	youtube
    url:	https://youtube.com/user/bodhiconnolly
    desc:	Subscribe on youube
    share_url:
    share_title:
    share_link:

  - icon:	instagram
    url:	https://instagram.com/bodhiconnolly
    desc:	Follow me on instagram
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/bodhiconnolly
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

